### ISSUE TITLE
Evolve doesn't work on subclassed DBs

### ISSUE THREAD

**Issue by MiguelSR** [keredson/peewee-db-evolve#19]
Hello!

My db connection uses a custom class that inherits from peewee.MySQLDatabase but has some custom behaviour. peewee-db-evolve looks only in the class name, so it fails when it compares to "MySQLDatabase" etc and it can't resolve it. That would be great if you use `isinstance(db, MySQLDatabase)` instead of `db.__class__.__name__ in ['MySQLDatabase']` and I think it would work OK.

I can do the PR if you're busy.

Thanks!!!
Miguel.

**Comment by keredson** [comment]
Yeah, send me a PR.  Thanks!

**Comment by keredson** [comment]
merged https://github.com/keredson/peewee-db-evolve/pull/20 and peewee-db-evolve-0.6.3 released
