### ISSUE TITLE
PyPI doesn't list newest version

### ISSUE THREAD

**Issue by S4NDW1CH** [keredson/peewee-db-evolve#32]
Latest version in PyPI is still listed as 0.6.8 and thus trying to install via `pip install peewee-db-evolve` results in error described in #29.

**Comment by willgdjones** [comment]
Same

**Comment by willgdjones** [comment]
Fix is: pip install git+https://github.com/keredson/peewee-db-evolve

**Comment by keredson** [comment]
fixed
