### ISSUE TITLE
Add peewee to requirements in setup file

### ISSUE THREAD

**Issue by EtienneDesticourt** [keredson/peewee-db-evolve#33]
Hi,

If you have the following requirements.txt file:
```
peewee
peewee-db-evolve
```
the installation will fail with the following traceback:

```
Collecting peewee-db-evolve (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/13/83/8c6435b2befc7a52a50ba83ee292890b2ae2f027eeeddc310b5018acca9f/peewee-db-evolve-3.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    colorama not installed
    peewee or herman not installed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_xc2cmgq/peewee-db-evolve/setup.py", line 16, in <module>
        version=__import__('peeweedbevolve').__version__,
      File "/tmp/pip-build-_xc2cmgq/peewee-db-evolve/peeweedbevolve.py", line 27, in <module>
        PW3 = not hasattr(pw, 'Clause')
    NameError: name 'pw' is not defined
```
because peewee-db-evolve does not list peewee in the install_requires attribute of its setup and therefore pip does not prioritize the installation of peewee.

Looking at the comment line 16 in the peeweedbevolve.py file it seems you'd anticipated this problem somewhat but you don't account for the fact that pw doesn't exist and is later used.
I'd advise moving the __version__ attribute to a secondary file, even if it doesn't comply with pep standards, or heavily refactoring peeweedbevolve.py

**Comment by keredson** [comment]
peewee-db-evolve-3.7.2 released!
