### ISSUE TITLE
Evolve setting existing values to new default value.

### ISSUE THREAD

**Issue by dsmurrell** [keredson/peewee-db-evolve#38]
I have a table 'Surveys' which has fields 'title' and 'description'.

The surveys all had existing titles and descriptions and were also `null=True`.

When removing the `null=True` and replacing it with `default=""`, evolve replaces all the existing values with `""`.

So for:

```
title = CharField(45, null=True)
description = CharField(500, null=True)
```

changing to:

```
title = CharField(45, default="")
description = CharField(500, default="")
```

evolve does:

```
UPDATE "surveys" SET "description" = %s; ['']
ALTER TABLE "surveys" ALTER COLUMN "description" SET NOT NULL;
UPDATE "surveys" SET "title" = %s; ['']
ALTER TABLE "surveys" ALTER COLUMN "title" SET NOT NULL;
```

Is this expected behaviour?

How can I get it to not replace the existing values?

**Comment by dsmurrell** [comment]
Ok, I seem to have found a workaround. That is to drop the `null=True` first, then evolve, then add the `default=""` for which the evolve doesn't seem to do anything.

This does mean that we need to migrate to prod twice being careful to to nuke data :)

**Comment by keredson** [comment]
well that is horrifying.  sorry about that. there should definitely be a `WHERE "title" IS NULL` on the `UPDATE` statement.

**Comment by keredson** [comment]
found the issue.  affects peewee3 only.

in peewee's schema migration library (which we use in places under peewee3) the migration function [`apply_default()`](https://github.com/coleifer/peewee/blob/00f32293e99bc7ad90f4706bd6b46d88f200b431/playhouse/migrate.py#L202) applies the default for all values, not just where they're currently null.  that seems wrong, but maybe i'm not understanding the intent.

should have a patch out soon to work around.

thanks for the bug report!

**Comment by keredson** [comment]
peewee-db-evolve-3.7.3 released

**Comment by dsmurrell** [comment]
That was fast, thank you!

And thanks for the extremely useful peewee-db-evolve!

**Comment by willgdjones** [comment]
Seconded @keredson !
