### ISSUE TITLE
Fails to evolve when using PooledPostgresqlExtDatabase

### ISSUE THREAD

**Issue by Gystark** [keredson/peewee-db-evolve#40]
First of all, thank you for publishing this great package!

Line 625 returns all tables to be added, including internal Peewee ones when using `PooledPostgresqlExtDatabase`. This produces the following error:
![image](https://user-images.githubusercontent.com/7481085/65627190-be419b00-dfc6-11e9-91f9-b46f30119018.png)

Interestingly, `evolve()` fails with the same error even when `PooledPostgresqlExtDatabase` is only imported but not used.

I have the following relevant packages installed:
```
peewee==3.11.2
psycopg2-binary==2.8.3
peewee-db-evolve==3.7.3
```

### A simple example that reproduces this issue:

```
from peeweedbevolve import evolve
from peewee import Model, CharField
from playhouse.pool import PooledPostgresqlExtDatabase


db = PooledPostgresqlExtDatabase("sqltest", user="postgres",
                                 password="postgres",
                                 host="localhost", port=5432)


class User(Model):
    name: str = CharField()

    class Meta:
        database = db


with db:
    evolve(db, interactive=True)
```

**Comment by AlexisMunera98** [comment]
You already resolve the problem? I have the same problem.

**Comment by Gystark** [comment]
@AlexisMunera98 I did find a workaround, but not a proper solution: if you move `from peeweedbevolve import evolve` below `from playhouse.pool import PooledPostgresqlExtDatabase` , you should be able to run `evolve()`.

**Comment by AlexisMunera98** [comment]
Works like a charm! Thanks

**Comment by AlexisMunera98** [comment]
Please close the issue

**Comment by keredson** [comment]
thanks for the bug report and the min example!

unclear what's going on here.  `BaseFTSModel` from the error msg is from peewee's sqlite database engine.

glad there's a workaround.  going to keep this open tho.

**Comment by silasary** [comment]
It looks like this happens if `peeweedbevolve` is imported before playhouse.
This means that the playhouse Base Classes are caught by `_add_model_hook`.

The best solution to this would probably to automatically add `BaseFTSModel` to the list of Models to never migrate.

**Comment by keredson** [comment]
@silasary thanks for the debugging!  added a filter for all the models in `playhouse.sqlite_ext`.  i also added `PooledPostgresqlExtDatabase` to the unit tests.

**Comment by keredson** [comment]
in release peewee-db-evolve-3.7.6
