### ISSUE TITLE
Support for rename columns

### ISSUE THREAD

**Issue by willgdjones** [keredson/peewee-db-evolve#44]
It would be helpful to have functionality for automatically renaming a column.

It is a challenging operation, because it might not be clear that the intention is to rename a column, only that a column has been removed and another column has been added.

I propose detecting whether a column is really being renamed with the following mechanism:
- Check that the only change removes a column and adds another column
- Check that the columns are of the same data type
- Add a confirmation step which asks for user confirmation if a possible renaming operation is detected.
- If yes:
    - Create a new column
    - Copy the existing data from the old column into the new column.
    - Delete old column.
- If no:
    - Create a new column
    - Delete old column.

I will get to work following this strategy and put a PR in. Do share any thoughts / ideas here!

**Comment by keredson** [comment]
Hey Will,

That's what the `aka` kwarg is for.  Add it to your column definition giving it the old column name to signal a rename.

Perhaps the documentation needs to be clearer? 

Derek

**Comment by willgdjones** [comment]
Oh I missed that! Is a link to some documentation that I'm missing?

Thanks for the fast response!

**Comment by keredson** [comment]
heh, i was just going to try to find you that link, but it would seem i never wrote any documentation for this version of this project.  =D  i'll have to get on that.

**Comment by keredson** [comment]
added to `README.md`
