### ISSUE TITLE
Require migrator to be exposed

### ISSUE THREAD

**Issue by kanekotic** [keredson/peewee-db-evolve#52]
I can see you have a comment on the [line](https://github.com/keredson/peewee-db-evolve/blob/388cda250392a2ad1d9cf0b7f23c4c2f3030b507/peeweedbevolve.py#L613).

I would be interested in passing the migrator as a parameter as I have a `PostgreSQL` database in a `Flask` app. The database is initialized through the connection string. So when I try to run `evolve` I get:
```
    raise Exception("could not auto-detect migrator for %s - please provide one via the migrator kwarg" % repr(db.__class__.__name__))
Exception: could not auto-detect migrator for 'Proxy' - please provide one via the migrator kwarg
```
Should I do a PR with this change?

**Comment by keredson** [comment]
SGTM!

**Comment by kanekotic** [comment]
cool @keredson I will prepare a PR and share if so :)
