### ISSUE TITLE
primary key tried to evolve when nothin changed

### ISSUE THREAD

**Issue by neopunisher** [keredson/peewee-db-evolve#8]
```
Traceback (most recent call last):
  File "evolve.py", line 13, in <module>
    config.db.evolve()
  File "/usr/local/lib/python2.7/dist-packages/peeweedbevolve.py", line 479, in evolve
    to_run = calc_changes(db)
  File "/usr/local/lib/python2.7/dist-packages/peeweedbevolve.py", line 353, in calc_changes
    adds, deletes, renames, alter_statements = calc_column_changes(db, migrator, etn, ntn, ecols, defined_fields, foreign_keys_by_table[etn])
  File "/usr/local/lib/python2.7/dist-packages/peeweedbevolve.py", line 273, in calc_column_changes
    raise Exception("In table %s I don't know how to change %s into %s" % (repr(ntn), existing_col, defined_col))
Exception: In table u'click_stream' I don't know how to change ColumnMetadata(name=u'id', data_type=u'integer', null=False, primary_key=False, table=u'click_stream', default=u"nextval('click_stream_id_seq'::regclass)", max_length=None) into ColumnMetadata(name=u'id', data_type=u'integer', null=False, primary_key=True, table=u'click_stream', default=None, max_length=None)
```

**Comment by keredson** [comment]
re: our investigation, something did change:
```
ColumnMetadata(name=u'id', data_type=u'integer', null=False, primary_key=False, table=u'click_stream', default=u"nextval('click_stream_id_seq'::regclass)", max_length=None)
ColumnMetadata(name=u'id', data_type=u'integer', null=False, primary_key=True, table=u'click_stream', default=None, max_length=None)
```

note the database doesn't recognize the `id` field as a primary key field any more.  (offline carter and i confirmed that the database had lost it as a PK, not that peewee-db-evolve wasn't picking it up as a PK.)

peewee-db-evolve currently doesn't support changing a column from/to a PK, but should.  so leaving this open for future feature work.

**Comment by edricgarran** [comment]
I has the same issue while trying to evolve a model with a composite primary key, so I guess that's what not working.

**Comment by keredson** [comment]
resolved offline IIRC

**Comment by keredson** [comment]
@edricgarran that couldn't have been @neopunisher's issue as we don't use and composite primary keys.  if you can replicate something similar tho can you open a new issue?

**Comment by Torvaney** [comment]
I've also been having issues with composite pkeys. Current workaround is to add a separate pkey and a composite uniqueness constraint :/

**Comment by Torvaney** [comment]
I came across this issue today when attempting to run `evolve`:

```
Exception: In table u'table_name' I don't know how to change ColumnMetadata(..., primary_key=False, ...) into ColumnMetadata(..., primary_key=True, ...)
```

This was confusing, to me since the table did have a primary key and thus there should be no conflict. Upon further investigation, I think the cause is that the DB user running the migration didn't have appropriate access to `information_schema.table_constraints`.

As a result the query in `get_columns_by_table` (https://github.com/keredson/peewee-db-evolve/blob/388cda250392a2ad1d9cf0b7f23c4c2f3030b507/peeweedbevolve.py#L415), was returning FALSE for that field's `primary_key` in the linked query.

Sharing this in case anyone else comes across this issue in the future.
